spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL:}
      chat:
        options:
          model: ${OPENAI_CHAT_MODEL:}
      embedding:
        options:
          model: ${OPENAI_EMBEDDING_MODEL:}

